import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/header";
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Beauty Salon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
