from enum import Enum

class Status(Enum):
    SUCCESS = 'SUCCESS'
    FILLED = 'FILLED'
    NOT_FOUND = 'NOT_FOUND'
    UNAUTHORIZED = 'UNAUTHORIZED'

class Roles(Enum):
    ADMIN = 'ADMIN'
    USER = 'USER'
    SUPER_ADMIN = 'SUPER_ADMIN'

class AuthStatus(Enum):
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    INVALID_TOKEN = 'INVALID_TOKEN'
    INVALID_USER = 'INVALID_USER'
    INVALID_PASSWORD = 'INVALID_PASSWORD'
    INVALID_EMAIL = 'INVALID_EMAIL'
    INVALID_USERNAME = 'INVALID_USERNAME'
    INVALID_ROLE = 'INVALID_ROLE'
    INVALID_STATUS = 'INVALID_STATUS'
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
    INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD'
    TOKEN_EXPIRED = 'TOKEN_EXPIRED'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    FORBIDDEN = 'FORBIDDEN'

class OrderStatus(Enum):
    PENDING = 'PENDING'
    PROCESSING = 'PROCESSING'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'
    REFUNDED = 'REFUNDED'
    FAILED = 'FAILED'


class Profession(Enum):
    HAIR_STYLIST = 'HAIR_STYLIST'
    MAKEUP_ARTIST = 'MAKEUP_ARTIST'
    NAIL_TECHNICIAN = 'NAIL_TECHNICIAN'
    SKIN_CARE_SPECIALIST = 'SKIN_CARE_SPECIALIST'
    MASSAGE_THERAPIST = 'MASSAGE_THERAPIST'
    BARBER = 'BARBER'
    SPA_MASTER = 'SPA_MASTER'
